import type { NewsSource } from '@/src/types/ui';

export const defaultSources: NewsSource[] = [
  {
    id: 'reuters-rss',
    name: 'Reuters Finance',
    url: 'https://www.reuters.com',
    type: 'rss',
    category: 'finance',
    rssUrl: 'https://feeds.reuters.com/reuters/businessNews',
    crawlFrequency: 30,
    isActive: true,
    useProxy: false,
    respectRobotsTxt: true,
  },
  {
    id: 'marketwatch-rss',
    name: 'MarketWatch',
    url: 'https://www.marketwatch.com',
    type: 'rss',
    category: 'markets',
    rssUrl: 'https://www.marketwatch.com/rss/topstories',
    crawlFrequency: 45,
    isActive: true,
    useProxy: false,
    respectRobotsTxt: true,
  },
  {
    id: 'financial-times-scrape',
    name: 'Financial Times',
    url: 'https://www.ft.com',
    type: 'scrape',
    category: 'finance',
    crawlFrequency: 60,
    isActive: true,
    useProxy: false,
    respectRobotsTxt: true,
    selector: {
      title: 'h3, h2',
      content: 'p',
      date: 'time',
      author: 'span',
      image: 'img',
    },
  },
  {
    id: 'alpha-vantage-api',
    name: 'Alpha Vantage',
    url: 'https://www.alphavantage.co',
    type: 'api',
    category: 'finance',
    crawlFrequency: 120,
    isActive: false,
    useProxy: false,
    respectRobotsTxt: false,
    apiEndpoint: 'https://www.alphavantage.co/query',
  },
];
